### ISSUE TITLE
Can u tell me more

### ISSUE THREAD

**Issue by tdnet12434** [jaejunlee0538/g2o_ros#1]
I want to use this package but i have no idea how to create a ros cpp file inside this package.
I tried to edit tutorial_slam2d to publish on ros topic but failed even add executable to a ros node.
what should i do?

**Comment by jaejunlee0538** [comment]
Can you leave error message after `catkin_make`?

And did you follow the following steps?

```
$ cd catkin_ws/src
$ git clone https://github.com/jaejunlee0538/g2o_ros.git
$ cd g2o_ros
$ git submodule init
$ git submodule update
```

**Comment by tdnet12434** [comment]
I have done those step already. It work when i run example application directly in build folder, but i can't run any example file with rosrun. My plan was to create a src folder that have cpp files (maybe use tutorial_slam2d as template). I added that cpp for ros excecutable to Cmakelist but i'm lost. Maybe a example will be appreciated.:D

**Comment by tdnet12434** [comment]
Nevermind, It worked now!

I copy tutorial_slam2d to src folder. Modify CMakelist.txt
it's now like below.

```
INCLUDE_DIRECTORIES(${CSPARSE_INCLUDE_DIR})


ADD_LIBRARY(test4_library
  src/tutorial_slam2d/edge_se2_pointxy.cpp  
  src/tutorial_slam2d/se2.h                
  src/tutorial_slam2d/vertex_point_xy.h
  src/tutorial_slam2d/edge_se2.cpp    
  src/tutorial_slam2d/edge_se2_pointxy.h    
  src/tutorial_slam2d/vertex_se2.cpp
  src/tutorial_slam2d/edge_se2.h      
  src/tutorial_slam2d/rand.h                
  src/tutorial_slam2d/vertex_point_xy.cpp  
  src/tutorial_slam2d/vertex_se2.h
  src/tutorial_slam2d/parameter_se2_offset.h 
  src/tutorial_slam2d/parameter_se2_offset.cpp
  src/tutorial_slam2d/types_tutorial_slam2d.h 
  src/tutorial_slam2d/types_tutorial_slam2d.cpp
  src/tutorial_slam2d/simulator.h 
  src/tutorial_slam2d/simulator.cpp
  src/tutorial_slam2d/g2o_tutorial_slam2d_api.h
)
TARGET_LINK_LIBRARIES(test4_library ${catkin_LIBRARIES} core solver_csparse)


add_executable(test4 src/tutorial_slam2d/tutorial_slam2d.cpp)
target_link_libraries(test4 ${catkin_LIBRARIES} test4_library)


```

**Comment by jaejunlee0538** [comment]
Good!
You cannot run g2o executables from ROS because g2o is built independently from ROS.
So I added g2o binary output path to the PATH environment variable and they could be run thereafter.
I find your solution would be more simple. Thank you :D.
